WITH RANKEDSCORES AS (
SELECT Dev_ID, Difficulty, RANK() OVER (PARTITION BY Dev_ID ORDER BY SCORE desc) AS SCORE_RANK, SCORE 
FROM anitdb1.level_details
JOIN player_details ON player_details.P_ID = level_details.P_ID)
SELECT DEV_ID, SCORE_RANK, SCORE, DIFFICULTY
FROM RANKEDSCORES
WHERE SCORE_RANK <=3;
